### ISSUE TITLE
Lack of 'mime_type' field in Photo objects

### ISSUE THREAD

**Issue by trenta3** [python-botogram/botogram#125]
Hi! I can see from the documentation and from sources that the field `mime_type` is available on Audio, Video, Document and Voice, but not on Photo!
I have the need to save photos but without mime_type I have no easy way to set their extension.

Is this just a little typing mistake or is it more difficult to do than for other media types?

Great project btw, it really simplifies things a lot!

**Comment by DTRandom** [comment]
Good evening @trenta3, thanks for your appreciation, unfortunately it's not our fault if mime_type is not available for Photos at the moment, because no mime_type field exists for Photos in the Telegram Bot API as you can see [here](https://core.telegram.org/bots/api#chatphoto). As soon as Telegram implements it, we'll add it into botogram. Have a nice day.
The Botogram Team
